package lilylicious.thaumicequivalence.config;

import lilylicious.thaumicequivalence.utils.TELogger;
import net.minecraftforge.common.config.Configuration;

import java.io.File;

public class TEConfig
{
	public static boolean enableDebugLog;
	public static boolean removeRecipes;
	public static boolean enableRecipes;
	public static boolean enableResearch;
	public static boolean taintEMC;
	public static boolean shapedArcaneEMC;
	public static boolean shapelessArcaneEMC;
	public static boolean infusionEMC;
	public static boolean crucibleEMC;
	public static boolean aspectEMC;
	public static int aerValue;
	public static int terraValue;
	public static int ignisValue;
	public static int aquaValue;
	public static int ordoValue;
	public static int perditioValue;
	public static int shimmerLeafValue;
	public static int quicksilverValue;
	public static int cinderpearlValue;
	public static int amberValue;
	public static int brainValue;
	
	public static void init(File configFile)
	{
		Configuration config = new Configuration(configFile);
		try
		{
			config.load();

			//Modules
			enableRecipes = config.getBoolean("recipes", "modules", false, "Enable thaumcraft recipes for ProjectE items");
			enableResearch = config.getBoolean("research", "modules", false, "Enable thaumcraft research for ProjectE items");

			//EMC
			aspectEMC = config.getBoolean("aspectEMC", "emc", true, "Enable autogenerated EMC from aspects. DISABLING WILL BREAK OTHER EMC MAPPERS");
			shapedArcaneEMC = config.getBoolean("shapedArcaneRecipesEMC", "emc", true, "Enable autogenerated EMC from shaped arcane crafting table recipes");
			shapelessArcaneEMC = config.getBoolean("shapelessArcaneRecipesEMC", "emc", true, "Enable autogenerated EMC from shapeless arcane crafting table recipes");
			infusionEMC = config.getBoolean("infusionEMC", "emc", true, "Enable autogenerated EMC from infusion crafting recipes");
			crucibleEMC = config.getBoolean("crucibleEMC", "emc", true, "Enable autogenerated EMC from crucible recipes");
			taintEMC = config.getBoolean("taintEMC", "emc", true, "Enable autogenerated EMC for taint items (soil, fibres, etc)");

			//Default Values
			aerValue = config.getInt("aerValue", "defaultValues", 10, 0, 9999999, "The default value of aer");
			terraValue = config.getInt("terraValue", "defaultValues", 10, 0, 9999999, "The default value of terra");
			ignisValue = config.getInt("ignisValue", "defaultValues", 10, 0, 9999999, "The default value of ignis");
			aquaValue = config.getInt("aquaValue", "defaultValues", 10, 0, 9999999, "The default value of aqua");
			ordoValue = config.getInt("ordoValue", "defaultValues", 10, 0, 9999999, "The default value of ordo");
			perditioValue = config.getInt("perditioValue", "defaultValues", 10, 0, 9999999, "The default value of perditio");
			shimmerLeafValue = config.getInt("shimmerLeafValue", "defaultValues", 128, 0, 999999, "The default value of Shimmerleaf");
			quicksilverValue = config.getInt("quicksilverValue", "defaultValues", 128, 0, 999999, "The default value of Quicksilver WARNING CHANGING WITHOUT CHANGING SHIMMERLEAF MAY CAUSE DUPE ISSUES");
			cinderpearlValue = config.getInt("cinderpearlValue", "defaultValues", 128, 0, 999999, "The default value of Cinderpearl WARNING CHANGING WITHOUT CHANGING BLAZE POWDER MAY CAUSE DUPE ISSUES");
			amberValue = config.getInt("amberValue", "defaultValues", 128, 0, 999999, "The default value of Amber");
			brainValue = config.getInt("brainValue", "defaultValues", 128, 0, 999999, "The default value of Zombie Brains");
			
			//Difficulty
			removeRecipes = config.getBoolean("recipeRemoval", "difficulty", true, "Enable recipe removals");

			//Misc
			enableDebugLog = config.getBoolean("debugLogging", "misc", false, "Enable a more verbose debug logging");


			//archangelPedCooldown = config.getInt("archangelPedCooldown", "pedestalcooldown", 100, -1, Integer.MAX_VALUE, "Delay between Archangel Smite shooting arrows while in the pedestal.");

			//timePedMobSlowness = config.getFloat("timePedMobSlowness", "effects", 0.10F, 0.0F, 1.0F, "Factor the Watch of Flowing Time slows down mobs by while in the pedestal. Set to 1.0 for no slowdown.");
			TELogger.logInfo("Loaded configuration file.");
		} catch (Exception e)
		{
			TELogger.logFatal("Caught exception while loading config file!");
			e.printStackTrace();
		} finally
		{
			if (config.hasChanged())
			{
				config.save();
			}
		}
	}
}