package lilylicious.thaumicequivalence.utils;

import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;

public class AspectLists
{
    private static AspectList placeholderAspectList = new AspectList().add(Aspect.FIRE, 1);

    //Crafting
    public static AspectList philoStoneCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.ENERGY, 16);
    public static AspectList transTableCrafting = new AspectList().add(Aspect.ORDER, 15).add(Aspect.ENTROPY, 15);
    public static AspectList darkMatterCrafting = new AspectList().add(Aspect.EXCHANGE, 20).add(Aspect.ENERGY, 10).add(Aspect.DARKNESS, 10);
    public static AspectList dmAxeCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PLANT, 8);
    public static AspectList dmHammerCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.TOOL, 8);
    public static AspectList dmHoeCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PLANT, 8);
    public static AspectList dmShearsCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.TOOL, 4);
    public static AspectList dmShovelCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.EARTH, 8);
    public static AspectList dmSwordCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.TOOL, 4).add(Aspect.ENERGY, 4);
    public static AspectList dmPickCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.TOOL, 8);
    public static AspectList dmFeetCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PROTECT, 16).add(Aspect.METAL, 16);
    public static AspectList dmLegsCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PROTECT, 24).add(Aspect.METAL, 16);
    public static AspectList dmChestCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PROTECT, 32).add(Aspect.METAL, 16);
    public static AspectList dmHelmCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PROTECT, 16).add(Aspect.METAL, 16);
    public static AspectList covalenceLowCrafting =  new AspectList().add(Aspect.ORDER, 4).add(Aspect.ENTROPY, 4);
    public static AspectList covalenceMedCrafting = new AspectList().add(Aspect.EXCHANGE, 3);
    public static AspectList covalenceHighCrafting = new AspectList().add(Aspect.EXCHANGE, 5);
    public static AspectList repairTalismanCrafting = new AspectList().add(Aspect.EXCHANGE, 2).add(Aspect.TOOL, 2).add(Aspect.CRAFT, 2);
    public static AspectList alchemicalChestCrafting = new AspectList().add(Aspect.EXCHANGE, 5).add(Aspect.VOID, 5);
    public static AspectList energyCondenserCrafting = new AspectList().add(Aspect.EXCHANGE, 7).add(Aspect.VOID, 5);
    public static AspectList collectorMk1Crafting = new AspectList().add(Aspect.EXCHANGE, 15);
    public static AspectList collectorMk2Crafting = new AspectList().add(Aspect.EXCHANGE, 20);
    public static AspectList collectorMk3Crafting = new AspectList().add(Aspect.EXCHANGE, 25);
    public static AspectList relayMk1Crafting = new AspectList().add(Aspect.EXCHANGE, 15);
    public static AspectList relayMk2Crafting = new AspectList().add(Aspect.EXCHANGE, 20);
    public static AspectList relayMk3Crafting = new AspectList().add(Aspect.EXCHANGE, 25);
    public static AspectList redMatterCrafting = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.ORDER, 5);
    public static AspectList ironBandCrafting = new AspectList().add(Aspect.ORDER, 5).add(Aspect.ENTROPY, 5);
    public static AspectList swiftWolfRingCrafting = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.FLIGHT, 5);
    public static AspectList harvestGoddessRingCrafting = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.PLANT, 10);
    public static AspectList zeroRingCrafting = new AspectList().add(Aspect.EXCHANGE, 10); // What else?
    public static AspectList ignitionRingCrafting = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.FIRE, 10);
    public static AspectList arcanaRingCrafting = new AspectList().add(Aspect.EXCHANGE, 15).add(Aspect.AURA, 15);
    public static AspectList timeWatchCrafting = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.DARKNESS, 5).add(Aspect.LIGHT, 5);
    public static AspectList kleinStarEin = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.ENERGY, 5);
    public static AspectList kleinStarZwei = new AspectList().add(Aspect.EXCHANGE, 12).add(Aspect.ENERGY, 7);
    public static AspectList kleinStarDrei = new AspectList().add(Aspect.EXCHANGE, 14).add(Aspect.ENERGY, 9);
    public static AspectList kleinStarVier = new AspectList().add(Aspect.EXCHANGE, 15).add(Aspect.ENERGY, 12);
    public static AspectList kleinStarSphereCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.ENERGY, 15);
    public static AspectList kleinStarOmegaCrafting = new AspectList().add(Aspect.EXCHANGE, 20).add(Aspect.ENERGY, 20);
    public static AspectList rmAxeCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PLANT, 8);
    public static AspectList rmHammerCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.TOOL, 8);
    public static AspectList rmHoeCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PLANT, 8);
    public static AspectList rmShearsCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.TOOL, 4);
    public static AspectList rmShovelCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.EARTH, 8);
    public static AspectList rmSwordCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.TOOL, 4).add(Aspect.ENERGY, 4);
    public static AspectList rmPickCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.TOOL, 8);
    public static AspectList rmBootsCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PROTECT, 16).add(Aspect.METAL, 16);
    public static AspectList rmLegsCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PROTECT, 24).add(Aspect.METAL, 16);
    public static AspectList rmChestCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PROTECT, 32).add(Aspect.METAL, 16);
    public static AspectList rmHelmCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.PROTECT, 16).add(Aspect.METAL, 16);
    public static AspectList gemBootsCrafting = new AspectList().add(Aspect.EXCHANGE, 25).add(Aspect.PROTECT, 20).add(Aspect.METAL, 25);
    public static AspectList gemLegsCrafting = new AspectList().add(Aspect.EXCHANGE, 25).add(Aspect.PROTECT, 30).add(Aspect.METAL, 25);
    public static AspectList gemChestCrafting = new AspectList().add(Aspect.EXCHANGE, 25).add(Aspect.PROTECT, 40).add(Aspect.METAL, 25);
    public static AspectList gemHelmCrafting = new AspectList().add(Aspect.EXCHANGE, 25).add(Aspect.PROTECT, 20).add(Aspect.METAL, 25);
    public static AspectList morningstarCrafting = new AspectList().add(Aspect.EXCHANGE, 30).add(Aspect.TOOL, 30);
    public static AspectList katarCrafting = new AspectList().add(Aspect.EXCHANGE, 30).add(Aspect.TOOL, 30);
    public static AspectList interdictionTorchCrafting = new AspectList().add(Aspect.EXCHANGE, 5).add(Aspect.MECHANISM, 5);
    public static AspectList energCondenserMk2Crafting = new AspectList().add(Aspect.EXCHANGE, 5).add(Aspect.MECHANISM, 5);
    public static AspectList dmPedestalCrafting = new AspectList().add(Aspect.EXCHANGE, 5).add(Aspect.MECHANISM, 5);
    public static AspectList alchCoal = new AspectList().add(Aspect.FIRE, 2).add(Aspect.ENERGY, 4);
    public static AspectList mobiusFuel = new AspectList().add(Aspect.FIRE, 5).add(Aspect.ENERGY, 8);
    public static AspectList aeternalisFuel = new AspectList().add(Aspect.FIRE, 10).add(Aspect.ENERGY, 16);
    public static AspectList blackHoleCrafting = new AspectList().add(Aspect.EXCHANGE, 12).add(Aspect.TOOL, 10);
    public static AspectList voidRingCrafting = new AspectList().add(Aspect.EXCHANGE, 12).add(Aspect.VOID, 16);
    public static AspectList novaCatalystCrafting = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.ENERGY, 16);
    public static AspectList novaCataclysmCrafting = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.ENERGY, 20);
    public static AspectList dmFurnaceCrafting = new AspectList().add(Aspect.EXCHANGE, 7).add(Aspect.MECHANISM, 10);
    public static AspectList rmFurnaceCrafting = new AspectList().add(Aspect.EXCHANGE, 12).add(Aspect.MECHANISM, 20);
    public static AspectList whiteAlchBagCrafting = new AspectList().add(Aspect.EXCHANGE, 15).add(Aspect.VOID, 15);
    public static AspectList lowDivinerCrafting = new AspectList().add(Aspect.EXCHANGE, 3).add(Aspect.SENSES, 3);
    public static AspectList medDivinerCrafting = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.SENSES, 10);
    public static AspectList highDivinerCrafting = new AspectList().add(Aspect.EXCHANGE, 16).add(Aspect.ENERGY, 16);
    public static AspectList mercurialEyeCrafting = new AspectList().add(Aspect.EXCHANGE, 15).add(Aspect.CRAFT, 10);
    public static AspectList densityGemCrafting = new AspectList().add(Aspect.EXCHANGE, 5).add(Aspect.ENTROPY, 10).add(Aspect.CRYSTAL, 5);
    public static AspectList bodyStoneCrafting = new AspectList().add(Aspect.EXCHANGE, 5).add(Aspect.TOOL, 5);
    public static AspectList soulStoneCrafting = new AspectList().add(Aspect.EXCHANGE, 5).add(Aspect.TOOL, 5);
    public static AspectList mindStoneCrafting = new AspectList().add(Aspect.EXCHANGE, 5).add(Aspect.TOOL, 5);
    public static AspectList lifeStoneCrafting = new AspectList().add(Aspect.EXCHANGE, 20).add(Aspect.TOOL, 10);
    public static AspectList evertideAmuletCrafting = new AspectList().add(Aspect.EXCHANGE, 7).add(Aspect.WATER, 5);
    public static AspectList volcaniteAmuletCrafting = new AspectList().add(Aspect.EXCHANGE, 7).add(Aspect.FIRE, 5);
    public static AspectList destructionCatalystCrafting = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.TOOL, 5).add(Aspect.ENERGY, 5);
    public static AspectList hyperkineticLensCrafting = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.TOOL, 10).add(Aspect.ENERGY, 15);
    public static AspectList catalyticLensCrafting = new AspectList().add(Aspect.EXCHANGE, 10).add(Aspect.TOOL, 15).add(Aspect.ENERGY, 30);
    public static AspectList transmutationTabletCrafting = new AspectList().add(Aspect.EXCHANGE, 30).add(Aspect.TOOL, 15);
}